/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs and kept here so the
// project type-checks cleanly from a fresh workspace.
